version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test
    test: 
         docker:
             - image: circleci/node:10-browsers
         steps:
              - run:
                   name: Install local dependencies
                   command: npm install
